name: Create Release Asset

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Module Zip
        run: |
          zip -r black-flag-token-bar.zip . -x ".git/*" ".github/*" "README.md" "LICENSE"

      - name: Upload Zip to Release
        uses: softprops/action-gh-release@v1
        with:
          files: black-flag-token-bar.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
