name: Update Foundry Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Foundry VTT Package Release
        uses: Varriount/foundry-vtt-package-release@v1.1
        with:
          package-id: black-flag-token-bar
          api-key: ${{ secrets.FOUNDRY_API_KEY }}
          tag: ${{ github.event.release.tag_name }}
          manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
