name: Update Foundry Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update Foundry Website
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.FOUNDRY_API_KEY }}" \
          -d '{
            "id": "black-flag-token-bar",
            "release": {
              "version": "1.1.1",
              "manifest": "https://raw.githubusercontent.com/ghost00-Ricgames/black-flag-token-bar/main/module.json",
              "notes": "https://github.com/ghost00-Ricgames/black-flag-token-bar/releases/tag/1.1.2",
              "compatibility": {
                "minimum": "13",
                "verified": "13"
              }
            }
          }'
